### ISSUE TITLE
Start record a track by clicking on the control 

### ISSUE THREAD

**Issue by lesnoj** [dj0001/Leaflet.mytrack#2]
Hello!
Thank you! You wrote a great plugin! It's very useful! I would like to use your plugin in my project.
 I'm haunted by the start this plugin. Recording a track in your plugin starts as soon as the page loads.
I put another control on tha map in my project. Alas, I'm a beginner in coding((. I want to ask you, how I need to change the code, that start recording a track by clicking on the control on the map, and stop recording and resume recording?

**Comment by dj0001** [comment]
In index.html:
karte.locate(...) starts recording
use [karte.stopLocate()](https://leafletjs.com/reference-1.4.0.html#map-stoplocate) to stop recording in your control

`<button onclick='karte.locate({watch: true, enableHighAccuracy: true})'>start</button>
<button onclick='karte.stopLocate()'>stop</button>`
